version: '3.8'
services:


  redis:
    image: redis:7.4.1-alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - app-network      
    volumes:
      - redis-data:/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
