services:
 
  shorty-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
      image: redis:7.4.1-alpine
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - app-network      
      volumes:
        - redis-data:/data

networks:
  app-network:
    external: true
    driver: bridge

volumes:
  redis-data: