---
spring:
  redis:
    test: profile-dev
    host: ${SPRING_REDIS_HOST:172.19.0.2}
    port: 6379
    password: null
app:
  name: shorty-dev
  version: 1.0.0
  author:
    name: Fernando Viel
    email: fviel1982@gmail.com